// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Autos
{
    public string Color { get; set; }

    public int Id { get; set; }

    public string Marca { get; set; }

    public string Modelo { get; set; }

    public int Puerta { get; set; }

    public int IdCochera { get; set; }

    public virtual Cocheras IdCocheraNavigation { get; set; }
}