// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Data.Models;

public partial class Cocheras
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Autos> Autos { get; set; } = new List<Autos>();
}