// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Cliente
{
    public int Id { get; set; }

    public string RazonSocial { get; set; }

    public int Cuil { get; set; }

    public DateOnly Alta { get; set; }

    public int DireccionId { get; set; }
    [JsonIgnore]
    public virtual ICollection<ClienteXcuenta> ClienteXcuenta { get; set; } = new List<ClienteXcuenta>();
    [JsonIgnore]
    public virtual Direccion Direccion { get; set; }
}