// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class ClienteXcuenta
{
    public int Id { get; set; }

    public DateOnly Alta { get; set; }

    public string Rol { get; set; }

    public int ClienteId { get; set; }

    public int CuentaId { get; set; }
    [JsonIgnore]
    public virtual Cliente Cliente { get; set; }
    [JsonIgnore]
    public virtual Cuenta Cuenta { get; set; }
}