// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Cuenta
{
    public int Id { get; set; }

    public int NumeroCuenta { get; set; }

    public int Cbu { get; set; }

    public int TipoCuentaId { get; set; }

    public int BancoId { get; set; }
    [JsonIgnore]
    public virtual Banco Banco { get; set; }
    [JsonIgnore]
    public virtual ICollection<ClienteXcuenta> ClienteXcuenta { get; set; } = new List<ClienteXcuenta>();
    [JsonIgnore]
    public virtual TipoCuenta TipoCuenta { get; set; }
    [JsonIgnore]
    public virtual ICollection<Transaccion> TransaccionCuentaDestino { get; set; } = new List<Transaccion>();
    [JsonIgnore]
    public virtual ICollection<Transaccion> TransaccionCuentaOrigen { get; set; } = new List<Transaccion>();
}