// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Localidad
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int Cp { get; set; }

    public int IdProvincia { get; set; }
    [JsonIgnore]
    public virtual ICollection<Direccion> Direccion { get; set; } = new List<Direccion>();
    [JsonIgnore]
    public virtual Provincia IdProvinciaNavigation { get; set; }
}