// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Data.Models;

public partial class Provincia
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? IdPais { get; set; }
    [JsonIgnore]
    public virtual Pais IdPaisNavigation { get; set; }
    [JsonIgnore]
    public virtual ICollection<Localidad> Localidad { get; set; } = new List<Localidad>();
}